/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PedidoConfirmadoRouteImport } from './routes/pedido-confirmado'
import { Route as PedidoRouteImport } from './routes/pedido'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as GerenteRouteImport } from './routes/gerente'
import { Route as GarcomRouteImport } from './routes/garcom'
import { Route as CozinhaRouteImport } from './routes/cozinha'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoConfirmadoRoute = PedidoConfirmadoRouteImport.update({
  id: '/pedido-confirmado',
  path: '/pedido-confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoRoute = PedidoRouteImport.update({
  id: '/pedido',
  path: '/pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenteRoute = GerenteRouteImport.update({
  id: '/gerente',
  path: '/gerente',
  getParentRoute: () => rootRouteImport,
} as any)
const GarcomRoute = GarcomRouteImport.update({
  id: '/garcom',
  path: '/garcom',
  getParentRoute: () => rootRouteImport,
} as any)
const CozinhaRoute = CozinhaRouteImport.update({
  id: '/cozinha',
  path: '/cozinha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cozinha': typeof CozinhaRoute
  '/garcom': typeof GarcomRoute
  '/gerente': typeof GerenteRoute
  '/menu': typeof MenuRoute
  '/pedido': typeof PedidoRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cozinha': typeof CozinhaRoute
  '/garcom': typeof GarcomRoute
  '/gerente': typeof GerenteRoute
  '/menu': typeof MenuRoute
  '/pedido': typeof PedidoRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cozinha': typeof CozinhaRoute
  '/garcom': typeof GarcomRoute
  '/gerente': typeof GerenteRoute
  '/menu': typeof MenuRoute
  '/pedido': typeof PedidoRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cozinha'
    | '/garcom'
    | '/gerente'
    | '/menu'
    | '/pedido'
    | '/pedido-confirmado'
    | '/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cozinha'
    | '/garcom'
    | '/gerente'
    | '/menu'
    | '/pedido'
    | '/pedido-confirmado'
    | '/reset-password'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cozinha'
    | '/garcom'
    | '/gerente'
    | '/menu'
    | '/pedido'
    | '/pedido-confirmado'
    | '/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CozinhaRoute: typeof CozinhaRoute
  GarcomRoute: typeof GarcomRoute
  GerenteRoute: typeof GerenteRoute
  MenuRoute: typeof MenuRoute
  PedidoRoute: typeof PedidoRoute
  PedidoConfirmadoRoute: typeof PedidoConfirmadoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido-confirmado': {
      id: '/pedido-confirmado'
      path: '/pedido-confirmado'
      fullPath: '/pedido-confirmado'
      preLoaderRoute: typeof PedidoConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido': {
      id: '/pedido'
      path: '/pedido'
      fullPath: '/pedido'
      preLoaderRoute: typeof PedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerente': {
      id: '/gerente'
      path: '/gerente'
      fullPath: '/gerente'
      preLoaderRoute: typeof GerenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garcom': {
      id: '/garcom'
      path: '/garcom'
      fullPath: '/garcom'
      preLoaderRoute: typeof GarcomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cozinha': {
      id: '/cozinha'
      path: '/cozinha'
      fullPath: '/cozinha'
      preLoaderRoute: typeof CozinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CozinhaRoute: CozinhaRoute,
  GarcomRoute: GarcomRoute,
  GerenteRoute: GerenteRoute,
  MenuRoute: MenuRoute,
  PedidoRoute: PedidoRoute,
  PedidoConfirmadoRoute: PedidoConfirmadoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
